# Generated by Django 5.1.6 on 2025-02-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('github', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('started_date', models.DateField()),
                ('conclusion_date', models.DateField()),
            ],
        ),
    ]
