# Generated by Django 5.1.6 on 2025-02-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_artwork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoedits',
            name='video',
        ),
        migrations.AddField(
            model_name='videoedits',
            name='url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
