# Generated by Django 5.1.6 on 2025-02-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_artwork', '0002_remove_videoedits_video_videoedits_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoedits',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
