# Generated by Django 5.1.6 on 2025-02-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('video', models.FileField(upload_to='vfx_post')),
                ('date', models.DateField()),
            ],
        ),
    ]
