# Generated by Django 5.1.6 on 2025-02-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
