# Generated by Django 5.1.6 on 2025-02-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfx', '0002_videos_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='video',
        ),
        migrations.AddField(
            model_name='videos',
            name='video_url',
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
