# Generated by Django 5.1.6 on 2025-02-26 07:02

from django.db import migrations, models

import datetime
class Migration(migrations.Migration):

    dependencies = [
        ('vfx', '0003_remove_videos_video_videos_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='posted_date',
            field=models.DateField(default=datetime.date.today()),
            preserve_default=False,
        ),
    ]
