# Generated by Django 5.1.6 on 2025-02-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blenderpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blender_posts')),
                ('date', models.DateField()),
                ('details', models.CharField(max_length=100)),
            ],
        ),
    ]
