# Generated by Django 5.1.6 on 2025-02-26 04:54

from django.db import migrations, models

import datetime
class Migration(migrations.Migration):

    dependencies = [
        ('blender', '0002_blenderpost_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blenderpost',
            name='posted_date',
            field=models.DateField(default=datetime.date.today()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blenderpost',
            name='details',
            field=models.CharField(max_length=500),
        ),
    ]
